server {
    listen 8081;
    server_name _;

    location ~ /\.env { deny all; return 404; }
    location ~ /\.git { deny all; return 404; }
    location ~ /\.local-data { deny all; return 404; }

    error_page 502 503 504 /tsapp-offline.html;
    location = /tsapp-offline.html {
        root /var/www;
        internal;
    }

    location / {
        proxy_intercept_errors on;
        proxy_pass http://127.0.0.1:2001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 120s;
        proxy_connect_timeout 2s;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
